// get cart-
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";

// add cart-
export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERROR = "ADD_CART_ERROR";

// update cart-
export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_ERROR = "UPDATE_CART_ERROR";

// delete cart-
export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_ERROR = "DELETE_CART_ERROR";

// delete all cart-
export const DELETE_ALL_CART_REQUEST = "DELETE_ALL_CART_REQUEST";
export const DELETE_ALL_CART_SUCCESS = "DELETE_ALL_CART_SUCCESS";
export const DELETE_ALL_CART_ERROR = "DELETE_ALL_CART_ERROR";