// get cart-
export const GET_ADMIN_PRODUCT_REQUEST = "GET_ADMIN_PRODUCT_REQUEST";
export const GET_ADMIN_PRODUCT_SUCCESS = "GET_ADMIN_PRODUCT_SUCCESS";
export const GET_ADMIN_PRODUCT_ERROR = "GET_ADMIN_PRODUCT_ERROR";

// add new product-
export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR";

// add new product-
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

// delete new product-
export const DELETE_NEW_PRODUCT_REQUEST = "DELETE_NEW_PRODUCT_REQUEST";
export const DELETE_NEW_PRODUCT_SUCCESS = "DELETE_NEW_PRODUCT_SUCCESS";
export const DELETE_NEW_PRODUCT_ERROR = "DELETE_NEW_PRODUCT_ERROR";